project_id = "lljnbysgcwvkhlnaqxtt"

[functions.novu-email]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.sso-magic-link]
verify_jwt = false

[functions.hubspot-contact-sync]
verify_jwt = false