/**
 * Caderno de Erros v2 — domain types.
 *
 * Source of truth for names/enums: docs/specs/00-contratos-canonicos.md §2
 *
 * DbReason is NOT duplicated here — import from src/lib/errorNotebookReasons.ts.
 */

import type { DbReason } from '@/lib/errorNotebookReasons';

// ─── Re-export for convenience (consumers may import from here) ───
export type { DbReason };

// ─── Canonical enums (§2 contratos canônicos) ───

/** Confidence level captured at answer time and at review time. */
export type Confidence = 'baixa' | 'media' | 'alta';

/**
 * Self-grade selected by the student after re-solving a question in the review
 * session. Maps to SM-2 quality values: errei=0, dificil=2, bom=3, facil=4.
 */
export type ReviewOutcome = 'errei' | 'dificil' | 'bom' | 'facil';

/**
 * Full set of values that `error_notebook.last_review_outcome` can hold,
 * including system-generated states beyond the student-selectable ReviewOutcome.
 */
export type LastReviewOutcome =
  | ReviewOutcome
  | 'snoozed'
  | 'awaiting_lesson'
  | 'leech_blocked';

// ─── SRS state (returned by schedule_next_review_guarded) ───

/**
 * SRS fields returned by `schedule_next_review_guarded`.
 * Mirrors the jsonb payload defined in docs/specs/00-contratos-canonicos.md §1.
 */
export interface SrsState {
  /** ISO timestamptz — next review due date (source of truth for scheduling). */
  srsDueAt: string;
  /** Current interval in days. */
  srsInterval: number;
  /** Consecutive successful review count. */
  srsReps: number;
  /** Ease factor (float, >= 1.3). */
  srsEase: number;
  /** True when mastery conditions are met (srs_reps >= 3 AND interval >= 21 AND confidence ok). */
  mastered: boolean;
  /** True when srs_lapses >= LEECH_THRESHOLD (4). Entry is blocked from re-testing. */
  isLeech: boolean;
}

// ─── Bulk add ───

/**
 * Payload for a single entry in `add_to_notebook_bulk_guarded`.
 * Mirrors the jsonb schema documented in docs/specs/04-auto-triage-confidence.md §6.1.
 * All fields required except learningText (nullable) and questionNumber (nullable).
 */
export interface BulkAddEntry {
  question_id: string;
  simulado_id: string;
  reason: DbReason;
  was_correct: boolean;
  learning_text: string | null;
  question_number: number | null;
  question_text: string | null;
  simulado_title: string | null;
  area: string | null;
  theme: string | null;
}

/**
 * Result of `add_to_notebook_bulk_guarded`.
 * `entryIds` lists the UUIDs of entries effectively created or resurrected
 * (soft-delete undone). `skipped` entries are NOT included.
 */
export interface BulkAddResult {
  /** Number of new entries created (including soft-delete resurrections). */
  added: number;
  /** Number of entries that already existed and were left unchanged. */
  skipped: number;
  /** UUIDs of the entries in `added`. May be empty if the RPC omits it. */
  entryIds: string[];
}

// ─── Review attempt ───

/**
 * Parameters for `record_review_attempt_guarded`.
 */
export interface RecordReviewAttemptParams {
  entryId: string;
  /** The option the student selected during review (null if answered from memory without picking). */
  selectedOptionId: string | null;
  wasCorrect: boolean;
  confidence: Confidence;
  /** Student's self-assessed difficulty. */
  selfGrade: ReviewOutcome;
}

// ─── Phase 2: Insights ───

/**
 * Canonical insight type enum (§12 contratos canônicos / spec 06 §A.1).
 * Maps to the five insight categories generated by caderno-pattern-insights.
 */
export type InsightType =
  | 'weak_area'
  | 'dominant_cause'
  | 'recurring_confusion'
  | 'overconfidence'
  | 'roi';

/**
 * A single diagnostic insight returned by the caderno-pattern-insights edge function.
 * Shape mirrors PatternInsight in spec 06 §A.3.
 */
export interface Insight {
  /** Stable identifier — e.g. 'weak-area', 'roi', etc. */
  id: string;
  type: InsightType;
  severity: 'critical' | 'attention' | 'positive' | 'info';
  title: string;
  /** 2–4 sentences; markdown allowed. */
  body: string;
  /** Highlighted metric (e.g. "1/7", "+18pp", "62%"). */
  metric?: string;
  /** Markdown table — only present for recurring_confusion insights. */
  comparison_table?: string;
  cta: { label: string; href: string } | null;
  /** Raw data that generated the insight — for debug/traceability. */
  data: Record<string, unknown>;
}

// ─── Phase 2: Flashcards ───

/**
 * Student-selectable outcome when reviewing a flashcard.
 * Mirrors ReviewOutcome; kept as a distinct alias so consumers are explicit
 * about which context the outcome belongs to.
 */
export type FlashcardReviewOutcome = 'errei' | 'dificil' | 'bom' | 'facil';

/** A flashcard deck (from the `decks` table). */
export interface Deck {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/** A flashcard item (from the `flashcards` table). */
export interface Flashcard {
  id: string;
  deck_id: string;
  user_id: string;
  /** Markdown content for the front face. */
  front_md: string;
  /** Markdown content for the back face. */
  back_md: string;
  /** Public / signed URL for a front-face image (optional). */
  front_image_url: string | null;
  /** Public / signed URL for a back-face image (optional). */
  back_image_url: string | null;
  /** Source entry in error_notebook (optional link). */
  entry_id: string | null;
  /** Source question (optional link). */
  question_id: string | null;
  /** ISO timestamptz — next SRS review due (flashcard-level SM-2-lite). */
  srs_due_at: string | null;
  srs_interval: number;
  srs_reps: number;
  srs_ease: number;
  mastered_at: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/** Payload for creating a new flashcard. */
export interface CreateFlashcardPayload {
  deck_id: string;
  front_md: string;
  back_md: string;
  front_image_url?: string | null;
  back_image_url?: string | null;
  entry_id?: string | null;
  question_id?: string | null;
}

/** Partial payload for updating an existing flashcard. */
export type UpdateFlashcardPayload = Partial<
  Pick<Flashcard, 'deck_id' | 'front_md' | 'back_md' | 'front_image_url' | 'back_image_url'>
>;

// ─── Phase 2: User Notes ───

/** A student note (from the `user_notes` table). */
export interface UserNote {
  id: string;
  user_id: string;
  title: string;
  /** Markdown body. */
  body_md: string;
  question_id: string | null;
  simulado_id: string | null;
  area: string | null;
  theme: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/** Payload for creating a new note. */
export interface CreateNotePayload {
  title: string;
  body_md: string;
  question_id?: string | null;
  simulado_id?: string | null;
  area?: string | null;
  theme?: string | null;
}

/** Partial payload for updating an existing note. */
export type UpdateNotePayload = Partial<Pick<UserNote, 'title' | 'body_md' | 'area' | 'theme'>>;

// ─── Phase 2: Favorites ───

/** A favorited question (from the `question_favorites` table). */
export interface QuestionFavorite {
  id: string;
  user_id: string;
  question_id: string;
  simulado_id: string | null;
  area: string | null;
  theme: string | null;
  created_at: string;
}

/** Payload for adding a favorite. */
export interface AddFavoritePayload {
  question_id: string;
  simulado_id?: string | null;
  area?: string | null;
  theme?: string | null;
}

// ─── Phase 4: Confidence Calibration ───

/**
 * A single bucket in the calibration response.
 * `accuracy` is null when `total` is 0 (no answers in that confidence level).
 */
export interface ConfidenceCalibrationBucket {
  confidence: Confidence;
  total: number;
  correct: number;
  accuracy: number | null;
}

/**
 * Overall metacognition indicators.
 *   - `total_answered_with_confidence`: total questions where the student declared a confidence level.
 *   - `alta_but_wrong`: declared "alta" but answered incorrectly (overconfidence signal).
 *   - `baixa_but_correct`: declared "baixa" but answered correctly (underconfidence signal).
 */
export interface ConfidenceCalibrationOverall {
  total_answered_with_confidence: number;
  alta_but_wrong: number;
  baixa_but_correct: number;
}

/**
 * Full payload returned by `get_confidence_calibration(p_user_id)` RPC.
 */
export interface ConfidenceCalibration {
  buckets: ConfidenceCalibrationBucket[];
  overall: ConfidenceCalibrationOverall;
}
