// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated. Reconnect this MCP server and sign in." }],
  isError: true
};

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Simulados profile: name, email, and access segment (guest, standard/aluno, or pro).",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("full_name, email, segment, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-simulados.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_simulados_default = defineTool2({
  name: "list_simulados",
  title: "List simulados",
  description: "List the mock exams (simulados) the signed-in user can see, newest first. Includes title, status, question count, duration, and execution window.",
  inputSchema: {
    limit: z.number().int().optional().describe("Maximum number of simulados to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const capped = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("simulados").select(
      "id, title, sequence_number, status, questions_count, duration_minutes, execution_window_start, execution_window_end, results_release_at"
    ).order("sequence_number", { ascending: false }).limit(capped);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { simulados: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-performance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_performance_default = defineTool3({
  name: "get_my_performance",
  title: "Get my performance summary",
  description: "Return the signed-in user's overall performance summary: total attempts and average, best and last scores.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("user_performance_summary").select("total_attempts, avg_score, best_score, last_score, last_finished_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "No performance data yet. Complete a simulado first." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { performance: data }
    };
  }
});

// src/lib/mcp/tools/list-my-attempts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_attempts_default = defineTool4({
  name: "list_my_attempts",
  title: "List my attempts",
  description: "List the signed-in user's simulado attempts, most recent first, with status, score and answer counts.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Maximum number of attempts to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const capped = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("attempts").select(
      "id, simulado_id, status, attempt_type, score_percentage, total_correct, total_answered, is_within_window, started_at, finished_at"
    ).order("started_at", { ascending: false }).limit(capped);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { attempts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-error-notebook.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_error_notebook_default = defineTool5({
  name: "list_error_notebook",
  title: "List error notebook entries",
  description: "List the signed-in user's error notebook (caderno de erros) entries \u2014 questions they got wrong \u2014 newest first. Optionally filter by area. This is a PRO feature; non-PRO users see no entries.",
  inputSchema: {
    area: z3.string().optional().describe("Filter entries by medical area (e.g. 'Cl\xEDnica M\xE9dica')."),
    limit: z3.number().int().optional().describe("Maximum number of entries to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ area, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const capped = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("error_notebook").select("id, area, theme, reason, question_number, simulado_title, was_correct, created_at, next_review_at").is("deleted_at", null).order("created_at", { ascending: false }).limit(capped);
    if (area) query = query.eq("area", area);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lljnbysgcwvkhlnaqxtt";
var mcp_default = defineMcp({
  name: "simulados-sanarflix-mcp",
  title: "Simulados SanarFlix MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Simulados SanarFlix (ENAMED) platform. Each caller is a signed-in user; every tool returns only that user's data under their permissions. Use `list_simulados` to browse mock exams, `get_my_performance` for score summaries, `list_my_attempts` for attempt history, `get_my_profile` for account details, and `list_error_notebook` for the PRO error notebook.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_simulados_default, get_my_performance_default, list_my_attempts_default, list_error_notebook_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
