INSERT INTO public.enamed_cutoff_scores (institution_name, practice_scenario, specialty_name, cutoff_score_general, cutoff_score_quota) VALUES
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'ANESTESIOLOGIA', 92.0, 85.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'CIRURGIA GERAL', 87.0, 80.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'CLÍNICA MÉDICA', 86.0, 79.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'DERMATOLOGIA', 96.0, 89.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'GINECOLOGIA E OBSTETRÍCIA', 87.0, 78.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'INFECTOLOGIA', 89.0, 82.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'MEDICINA INTENSIVA', 82.0, 74.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'NEUROLOGIA', 93.0, 86.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'OFTALMOLOGIA', 94.0, 87.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'ORTOPEDIA E TRAUMATOLOGIA', 89.0, 81.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'OTORRINOLARINGOLOGIA', 92.0, 85.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'PATOLOGIA', 82.0, 72.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'PEDIATRIA', 83.0, 75.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'PSIQUIATRIA', 91.0, 84.0),
('Universidade Federal de Minas Gerais', 'Hospital das Clínicas da UFMG - HC/UFMG', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 91.0, 81.0),
('Universidade Federal de Minas Gerais', 'Sistema de Saúde do Município de Belo Horizonte', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 82.0, 73.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'ANESTESIOLOGIA', 91.0, 83.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'CIRURGIA GERAL', 85.0, 77.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'CLÍNICA MÉDICA', 84.0, 76.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'DERMATOLOGIA', 94.0, 86.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'GINECOLOGIA E OBSTETRÍCIA', 85.0, 76.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'MEDICINA INTENSIVA', 80.0, 73.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'NEUROLOGIA', 92.0, 84.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'OFTALMOLOGIA', 93.0, 83.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'ORTOPEDIA E TRAUMATOLOGIA', 87.0, 79.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'OTORRINOLARINGOLOGIA', 91.0, 83.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'PEDIATRIA', 82.0, 72.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'PSIQUIATRIA', 90.0, 82.0),
('Universidade Federal de Uberlândia', 'Hospital de Clínicas de Uberlândia', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 90.0, 80.0),
('Universidade Federal de Uberlândia', 'Sistema de Saúde do Município de Uberlândia', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 80.0, 71.0),
('Universidade Federal do Acre', 'Fundação Hospitalar Estadual do Acre', 'CIRURGIA GERAL', 82.0, 64.0),
('Universidade Federal do Acre', 'Fundação Hospitalar Estadual do Acre', 'CLÍNICA MÉDICA', 75.0, 57.0),
('Universidade Federal do Acre', 'Fundação Hospitalar Estadual do Acre', 'GINECOLOGIA E OBSTETRÍCIA', 80.0, 55.0),
('Universidade Federal do Acre', 'Fundação Hospitalar Estadual do Acre', 'ORTOPEDIA E TRAUMATOLOGIA', 80.0, 62.0),
('Universidade Federal do Acre', 'Fundação Hospitalar Estadual do Acre', 'PEDIATRIA', 74.0, 56.0),
('Universidade Federal do Acre', 'Sistema de Saúde do Município de Rio Branco', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 66.0, NULL),
('Universidade Federal do Amazonas - UFAM', 'Hospital Universitário Francisca Mendes', 'ANESTESIOLOGIA', 85.0, 68.0),
('Universidade Federal do Amazonas - UFAM', 'Hospital Universitário Francisca Mendes', 'CIRURGIA GERAL', 83.0, 67.0),
('Universidade Federal do Amazonas - UFAM', 'Hospital Universitário Francisca Mendes', 'CLÍNICA MÉDICA', 76.0, 60.0),
('Universidade Federal do Amazonas - UFAM', 'Hospital Universitário Francisca Mendes', 'GINECOLOGIA E OBSTETRÍCIA', 81.0, 60.0),
('Universidade Federal do Amazonas - UFAM', 'Hospital Universitário Francisca Mendes', 'MEDICINA INTENSIVA', 66.0, NULL),
('Universidade Federal do Amazonas - UFAM', 'Hospital Universitário Francisca Mendes', 'ORTOPEDIA E TRAUMATOLOGIA', 82.0, 67.0),
('Universidade Federal do Amazonas - UFAM', 'Hospital Universitário Francisca Mendes', 'PEDIATRIA', 74.0, 56.0),
('Universidade Federal do Amazonas - UFAM', 'Sistema de Saúde do Município de Manaus', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 68.0, 53.0),
('Universidade Federal do Cariri', 'Hospital Regional do Cariri', 'ANESTESIOLOGIA', 88.0, 79.0),
('Universidade Federal do Cariri', 'Hospital Regional do Cariri', 'CIRURGIA GERAL', 83.0, 71.0),
('Universidade Federal do Cariri', 'Hospital Regional do Cariri', 'CLÍNICA MÉDICA', 81.0, 72.0),
('Universidade Federal do Cariri', 'Hospital Regional do Cariri', 'GINECOLOGIA E OBSTETRÍCIA', 82.0, 70.0),
('Universidade Federal do Cariri', 'Hospital Regional do Cariri', 'MEDICINA INTENSIVA', 74.0, NULL),
('Universidade Federal do Cariri', 'Hospital Regional do Cariri', 'ORTOPEDIA E TRAUMATOLOGIA', 83.0, 71.0),
('Universidade Federal do Cariri', 'Hospital Regional do Cariri', 'PEDIATRIA', 78.0, 62.0),
('Universidade Federal do Cariri', 'Sistema de Saúde do Município de Barbalha', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 75.0, 57.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'ANESTESIOLOGIA', 91.0, 85.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'CIRURGIA GERAL', 86.0, 78.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'CLÍNICA MÉDICA', 85.0, 78.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'DERMATOLOGIA', 95.0, 88.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'GINECOLOGIA E OBSTETRÍCIA', 86.0, 76.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'INFECTOLOGIA', 89.0, 80.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'MEDICINA INTENSIVA', 80.0, NULL),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'NEUROLOGIA', 93.0, 86.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'OFTALMOLOGIA', 93.0, 85.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'ORTOPEDIA E TRAUMATOLOGIA', 87.0, 79.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'OTORRINOLARINGOLOGIA', 91.0, 83.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'PEDIATRIA', 81.0, 70.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'PSIQUIATRIA', 91.0, 83.0),
('Universidade Federal do Ceará', 'Hospital Universitário Walter Cantídio', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 89.0, 79.0),
('Universidade Federal do Ceará', 'Maternidade Escola Assis Chateaubriand', 'GINECOLOGIA E OBSTETRÍCIA', 86.0, 77.0),
('Universidade Federal do Ceará', 'Maternidade Escola Assis Chateaubriand', 'PEDIATRIA', 82.0, 72.0),
('Universidade Federal do Ceará', 'Sistema de Saúde do Município de Fortaleza', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 80.0, 70.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'ANESTESIOLOGIA', 90.0, 82.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'CIRURGIA GERAL', 86.0, 76.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'CLÍNICA MÉDICA', 83.0, 75.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'DERMATOLOGIA', 93.0, 85.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'GINECOLOGIA E OBSTETRÍCIA', 84.0, 73.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'MEDICINA INTENSIVA', 79.0, 69.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'NEUROLOGIA', 91.0, 83.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'OFTALMOLOGIA', 92.0, 82.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'ORTOPEDIA E TRAUMATOLOGIA', 86.0, 77.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'OTORRINOLARINGOLOGIA', 90.0, 81.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'PEDIATRIA', 81.0, 69.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'PSIQUIATRIA', 89.0, 81.0),
('Universidade Federal do Espírito Santo', 'Hospital Universitário Cassiano Antonio de Moraes', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 89.0, 78.0),
('Universidade Federal do Espírito Santo', 'Sistema de Saúde do Município de Vitória', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 79.0, 68.0),
('Universidade Federal do Estado do Rio de Janeiro', 'Hospital Universitário Gaffrée e Guinle', 'DERMATOLOGIA', 95.0, 88.0),
('Universidade Federal do Estado do Rio de Janeiro', 'Hospital Universitário Gaffrée e Guinle', 'INFECTOLOGIA', 88.0, 80.0),
('Universidade Federal do Estado do Rio de Janeiro', 'Hospital Universitário Gaffrée e Guinle', 'NEUROLOGIA', 92.0, 84.0),
('Universidade Federal do Estado do Rio de Janeiro', 'Hospital Universitário Gaffrée e Guinle', 'OTORRINOLARINGOLOGIA', 90.0, 81.0),
('Universidade Federal do Estado do Rio de Janeiro', 'Hospital Universitário Gaffrée e Guinle', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 89.0, 79.0),
('Universidade Federal do Maranhão - UFMA', 'Hospital Universitário da UFMA', 'MEDICINA DE EMERGÊNCIA', 72.0, 59.0),
('Universidade Federal do Maranhão - UFMA', 'Hospital Universitário da UFMA', 'OFTALMOLOGIA', 91.0, 78.0),
('Universidade Federal do Maranhão - UFMA', 'Hospital Universitário da UFMA', 'OTORRINOLARINGOLOGIA', 87.0, 71.0),
('Universidade Federal do Mato Grosso', 'Hospital Universitário Júlio Müller', 'ANESTESIOLOGIA', 87.0, 77.0),
('Universidade Federal do Mato Grosso', 'Hospital Universitário Júlio Müller', 'CIRURGIA GERAL', 83.0, 72.0),
('Universidade Federal do Mato Grosso', 'Hospital Universitário Júlio Müller', 'CLÍNICA MÉDICA', 80.0, 69.0),
('Universidade Federal do Mato Grosso', 'Hospital Universitário Júlio Müller', 'GINECOLOGIA E OBSTETRÍCIA', 83.0, 70.0),
('Universidade Federal do Mato Grosso', 'Hospital Universitário Júlio Müller', 'MEDICINA INTENSIVA', 76.0, NULL),
('Universidade Federal do Mato Grosso', 'Hospital Universitário Júlio Müller', 'ORTOPEDIA E TRAUMATOLOGIA', 83.0, 73.0),
('Universidade Federal do Mato Grosso', 'Hospital Universitário Júlio Müller', 'PEDIATRIA', 77.0, 62.0),
('Universidade Federal do Mato Grosso', 'Sistema de Saúde do Município de Cuiabá', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 76.0, 65.0),
('Universidade Federal do Pará', 'Hospital Universitário Bettina Ferro de Souza', 'DERMATOLOGIA', 91.0, 82.0),
('Universidade Federal do Pará', 'Hospital Universitário Bettina Ferro de Souza', 'MEDICINA DE EMERGÊNCIA', 66.0, NULL),
('Universidade Federal do Pará', 'Hospital Universitário Bettina Ferro de Souza', 'MEDICINA FÍSICA E REABILITAÇÃO', 75.0, 62.0),
('Universidade Federal do Paraná', 'Hospital de Clínicas da UFPR', 'INFECTOLOGIA', 89.0, 82.0),
('Universidade Federal do Paraná', 'Hospital de Clínicas da UFPR', 'MEDICINA DE EMERGÊNCIA', 83.0, 74.0),
('Universidade Federal do Paraná', 'Hospital de Clínicas da UFPR', 'MEDICINA ESPORTIVA', 86.0, 73.0),
('Universidade Federal do Paraná', 'Hospital de Clínicas da UFPR', 'PATOLOGIA', 82.0, 72.0),
('Universidade Federal do Paraná', 'Hospital de Clínicas da UFPR', 'PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL', 86.0, 72.0),
('Universidade Federal do Recôncavo da Bahia', 'Hospital de Santo Antônio de Jesus', 'CIRURGIA GERAL', 82.0, 71.0),
('Universidade Federal do Recôncavo da Bahia', 'Hospital de Santo Antônio de Jesus', 'CLÍNICA MÉDICA', 79.0, 69.0),
('Universidade Federal do Recôncavo da Bahia', 'Hospital de Santo Antônio de Jesus', 'GINECOLOGIA E OBSTETRÍCIA', 80.0, 67.0),
('Universidade Federal do Recôncavo da Bahia', 'Hospital de Santo Antônio de Jesus', 'PEDIATRIA', 76.0, 60.0),
('Universidade Federal do Recôncavo da Bahia', 'Sistema de Saúde do Município de Santo Antônio de Jesus', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 72.0, 55.0),
('Universidade Federal do Rio Grande do Norte', 'Hospital Universitário Onofre Lopes', 'DERMATOLOGIA', 93.0, 83.0),
('Universidade Federal do Rio Grande do Norte', 'Hospital Universitário Onofre Lopes', 'INFECTOLOGIA', 89.0, 79.0),
('Universidade Federal do Rio Grande do Norte', 'Hospital Universitário Onofre Lopes', 'MEDICINA DE EMERGÊNCIA', 76.0, 65.0),
('Universidade Federal do Rio Grande do Norte', 'Maternidade Escola Januário Cicco', 'GINECOLOGIA E OBSTETRÍCIA', 84.0, 73.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'MEDICINA DE EMERGÊNCIA', 84.0, 76.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'MEDICINA DO TRABALHO', 85.0, 73.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'MEDICINA ESPORTIVA', 87.0, 77.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'MEDICINA FÍSICA E REABILITAÇÃO', 82.0, 72.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'MEDICINA LEGAL E PERÍCIAS MÉDICAS', 82.0, 72.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'MEDICINA NUCLEAR', 89.0, 79.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'MEDICINA PREVENTIVA E SOCIAL', 83.0, 71.0),
('Universidade Federal do Rio Grande do Sul', 'Hospital de Clínicas de Porto Alegre', 'NEUROCIRURGIA', 88.0, 80.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'ANESTESIOLOGIA', 92.0, 85.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'DERMATOLOGIA', 96.0, 89.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'INFECTOLOGIA', 90.0, 82.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'MEDICINA DE EMERGÊNCIA', 82.0, 73.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'MEDICINA INTENSIVA', 80.0, 74.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'NEUROLOGIA', 93.0, 86.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'OTORRINOLARINGOLOGIA', 91.0, 84.0),
('Universidade Federal do Rio de Janeiro', 'Hospital Universitário Clementino Fraga Filho', 'PATOLOGIA', 82.0, 72.0),
('Universidade Federal do Rio de Janeiro', 'Instituto de Ginecologia - Maternidade Escola', 'GINECOLOGIA E OBSTETRÍCIA', 87.0, 78.0),
('Universidade Federal do Rio de Janeiro', 'Instituto de Puericultura e Pediatria Martagão Gesteira', 'PEDIATRIA', 84.0, 73.0),
('Universidade Federal do Rio de Janeiro', 'Sistema de Saúde do Município do Rio de Janeiro', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 80.0, 72.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'ANESTESIOLOGIA', 90.0, 81.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'CIRURGIA GERAL', 84.0, 75.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'CLÍNICA MÉDICA', 83.0, 75.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'GINECOLOGIA E OBSTETRÍCIA', 84.0, 74.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'MEDICINA INTENSIVA', 79.0, 69.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'NEUROLOGIA', 91.0, 82.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'ORTOPEDIA E TRAUMATOLOGIA', 86.0, 78.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'PEDIATRIA', 81.0, 70.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'PSIQUIATRIA', 89.0, 82.0),
('Universidade Federal do Triângulo Mineiro', 'Hospital de Clínicas da UFTM', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 89.0, 79.0),
('Universidade Federal do Triângulo Mineiro', 'Sistema de Saúde do Município de Uberaba', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 79.0, 69.0),
('Universidade Federal do Vale do São Francisco', 'Hospital Universitário', 'ANESTESIOLOGIA', 88.0, 76.0),
('Universidade Federal do Vale do São Francisco', 'Hospital Universitário', 'CIRURGIA GERAL', 83.0, 71.0),
('Universidade Federal do Vale do São Francisco', 'Hospital Universitário', 'CLÍNICA MÉDICA', 80.0, 67.0),
('Universidade Federal do Vale do São Francisco', 'Hospital Universitário', 'GINECOLOGIA E OBSTETRÍCIA', 82.0, 68.0),
('Universidade Federal do Vale do São Francisco', 'Hospital Universitário', 'MEDICINA INTENSIVA', 74.0, NULL),
('Universidade Federal do Vale do São Francisco', 'Hospital Universitário', 'ORTOPEDIA E TRAUMATOLOGIA', 83.0, 71.0),
('Universidade Federal do Vale do São Francisco', 'Hospital Universitário', 'PEDIATRIA', 77.0, 60.0),
('Universidade Federal do Vale do São Francisco', 'Sistema de Saúde do Município de Petrolina', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 74.0, 55.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'INFECTOLOGIA', 90.0, 83.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'MEDICINA DE EMERGÊNCIA', 82.0, 73.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'MEDICINA DO TRÁFEGO', 83.0, 73.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'MEDICINA ESPORTIVA', 87.0, 78.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'MEDICINA FÍSICA E REABILITAÇÃO', 79.0, 68.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'NEUROCIRURGIA', 88.0, 79.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'PATOLOGIA', 81.0, 73.0),
('Universidade de Brasília', 'Hospital Universitário de Brasília', 'PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL', 86.0, 75.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'ANESTESIOLOGIA', 91.0, 82.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'CIRURGIA GERAL', 85.0, 73.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'CLÍNICA MÉDICA', 83.0, 72.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'GINECOLOGIA E OBSTETRÍCIA', 84.0, 71.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'MEDICINA INTENSIVA', 78.0, 65.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'NEUROLOGIA', 91.0, 82.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'OFTALMOLOGIA', 92.0, 83.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'ORTOPEDIA E TRAUMATOLOGIA', 86.0, 74.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'OTORRINOLARINGOLOGIA', 89.0, 80.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'PEDIATRIA', 81.0, 66.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'PSIQUIATRIA', 89.0, 80.0),
('Universidade de Pernambuco', 'Hospital Universitário Oswaldo Cruz', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 88.0, 75.0),
('Universidade de Pernambuco', 'Sistema de Saúde do Município de Recife', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 75.0, 61.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'ANESTESIOLOGIA', 93.0, 86.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'CIRURGIA GERAL', 88.0, 81.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'CLÍNICA MÉDICA', 87.0, 81.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'DERMATOLOGIA', 96.0, 89.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'GENÉTICA MÉDICA', 93.0, 85.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'GINECOLOGIA E OBSTETRÍCIA', 88.0, 81.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'INFECTOLOGIA', 90.0, 83.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'MEDICINA INTENSIVA', 82.0, 77.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'NEUROLOGIA', 94.0, 87.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'OFTALMOLOGIA', 95.0, 88.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'ORTOPEDIA E TRAUMATOLOGIA', 90.0, 83.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'OTORRINOLARINGOLOGIA', 93.0, 86.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'PATOLOGIA', 83.0, 72.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'PEDIATRIA', 84.0, 77.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'PSIQUIATRIA', 92.0, 85.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMRP-USP', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 92.0, 84.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'ANESTESIOLOGIA', 93.0, 87.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'CIRURGIA GERAL', 89.0, 83.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'CLÍNICA MÉDICA', 88.0, 83.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'DERMATOLOGIA', 97.0, 91.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'GENÉTICA MÉDICA', 93.0, 86.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'GINECOLOGIA E OBSTETRÍCIA', 89.0, 83.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'INFECTOLOGIA', 91.0, 84.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'MEDICINA INTENSIVA', 83.0, 78.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'NEUROLOGIA', 95.0, 89.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'OFTALMOLOGIA', 95.0, 90.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'ORTOPEDIA E TRAUMATOLOGIA', 90.0, 84.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'OTORRINOLARINGOLOGIA', 93.0, 87.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'PATOLOGIA', 84.0, 74.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL', 87.0, 73.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'PEDIATRIA', 86.0, 79.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'PSIQUIATRIA', 92.0, 87.0),
('Universidade de São Paulo', 'Hospital das Clínicas da FMUSP', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 93.0, 85.0),
('Universidade de São Paulo', 'Sistema de Saúde do Município de Ribeirão Preto', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 82.0, 73.0),
('Universidade de São Paulo', 'Sistema de Saúde do Município de São Paulo', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 82.0, 73.0),
('Universidade do Estado do Amazonas', 'Hospital e Pronto-Socorro 28 de Agosto', 'ANESTESIOLOGIA', 86.0, 71.0),
('Universidade do Estado do Amazonas', 'Hospital e Pronto-Socorro 28 de Agosto', 'CIRURGIA GERAL', 83.0, 66.0),
('Universidade do Estado do Amazonas', 'Hospital e Pronto-Socorro 28 de Agosto', 'CLÍNICA MÉDICA', 76.0, 59.0),
('Universidade do Estado do Amazonas', 'Hospital e Pronto-Socorro 28 de Agosto', 'GINECOLOGIA E OBSTETRÍCIA', 81.0, 60.0),
('Universidade do Estado do Amazonas', 'Hospital e Pronto-Socorro 28 de Agosto', 'MEDICINA INTENSIVA', 67.0, NULL),
('Universidade do Estado do Amazonas', 'Hospital e Pronto-Socorro 28 de Agosto', 'ORTOPEDIA E TRAUMATOLOGIA', 82.0, 67.0),
('Universidade do Estado do Amazonas', 'Hospital e Pronto-Socorro 28 de Agosto', 'PEDIATRIA', 75.0, 57.0),
('Universidade do Estado do Amazonas', 'Sistema de Saúde do Município de Manaus', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 69.0, 53.0),
('Universidade do Estado do Pará', 'Centro de Ciências Biológicas e da Saúde da UEPA', 'CIRURGIA GERAL', 84.0, 69.0),
('Universidade do Estado do Pará', 'Centro de Ciências Biológicas e da Saúde da UEPA', 'CLÍNICA MÉDICA', 79.0, 66.0),
('Universidade do Estado do Pará', 'Centro de Ciências Biológicas e da Saúde da UEPA', 'GINECOLOGIA E OBSTETRÍCIA', 81.0, 65.0),
('Universidade do Estado do Pará', 'Centro de Ciências Biológicas e da Saúde da UEPA', 'MEDICINA INTENSIVA', 68.0, NULL),
('Universidade do Estado do Pará', 'Centro de Ciências Biológicas e da Saúde da UEPA', 'ORTOPEDIA E TRAUMATOLOGIA', 82.0, 68.0),
('Universidade do Estado do Pará', 'Centro de Ciências Biológicas e da Saúde da UEPA', 'PEDIATRIA', 75.0, 57.0),
('Universidade do Estado do Pará', 'Sistema de Saúde do Município de Belém', 'MEDICINA DE FAMÍLIA E COMUNIDADE', 74.0, 55.0);